print("____DAILY TRACKER________")
print("WELCOME to your daily tracker")
print("\n")
Fname = input("Enter First Name: ")
Lname =input("Enter Last name: " )
print("Continue to track your expenses", Fname, Lname)
print("MY EXPENSES:")
food = float(input("Enter the total amount spent on Food today: "))
transport = float(input("Enter Transport amount today: "))
other = float(input("Enter the ground amount for other items purchased: "))
total_expenses = print("The total expenses made today is GhC", food + transport + other)
